In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
# read the json file into a pandas DataFrame
df = pd.read_json('/content/drive/MyDrive/annotations.json')

In [ ]:

df['position'] = df['position'].str.rstrip('1234567890')
# print the DataFrame to verify
df

position    image  frame  \
0       standing        1      1   
1       standing        2      2   
2       standing        3      3   
3       standing        4      4   
4       standing        5      5   
...          ...      ...    ...   
120274      back  1506746   6746   
120275      back  1506747   6747   
120276      back  1506748   6748   
120277      back  1506749   6749   
120278      back  1506750   6750   

                                                    pose2  \
0       [[449.349365234375, 223.6246337890625, 0.99492...   
1       [[443.377197265625, 223.846435546875, 0.989061...   
2       [[787.5810546875, 270.7499694824219, 0.9706746...   
3       [[778.1063232421875, 269.86773681640625, 0.955...   
4       [[763.244384765625, 269.6915283203125, 0.95246...   
...                                                   ...   
120274  [[189.31475830078125, 149.04867553710938, 0.25...   
120275  [[178.88967895507812, 122.95089721679688, 0.26...   
120276  [[179.33627319335938, 123.41546630859375, 0.29...   
120277  [[178.23870849609375, 123.7001953125, 0.199709...   
120278  [[181.7613525390625, 124.66265869140625, 0.256...   

                                                    pose1  
0                                                     NaN  
1                                                     NaN  
2       [[594.29736328125, 60.15850830078125, 0.358740...  
3       [[579.4054565429688, 62.07275390625, 0.4552341...  
4       [[565.22314453125, 57.39752197265625, 0.498457...  
...                                                   ...  
120274                                                NaN  
120275                                                NaN  
120276                                                NaN  
120277                                                NaN  
120278                                                NaN  

[120279 rows x 5 columns]

In [ ]:
df["pose1"] = df["pose1"].fillna(method='ffill')
df

position    image  frame  \
0       standing        1      1   
1       standing        2      2   
2       standing        3      3   
3       standing        4      4   
4       standing        5      5   
...          ...      ...    ...   
120274      back  1506746   6746   
120275      back  1506747   6747   
120276      back  1506748   6748   
120277      back  1506749   6749   
120278      back  1506750   6750   

                                                    pose2  \
0       [[449.349365234375, 223.6246337890625, 0.99492...   
1       [[443.377197265625, 223.846435546875, 0.989061...   
2       [[787.5810546875, 270.7499694824219, 0.9706746...   
3       [[778.1063232421875, 269.86773681640625, 0.955...   
4       [[763.244384765625, 269.6915283203125, 0.95246...   
...                                                   ...   
120274  [[189.31475830078125, 149.04867553710938, 0.25...   
120275  [[178.88967895507812, 122.95089721679688, 0.26...   
120276  [[179.33627319335938, 123.41546630859375, 0.29...   
120277  [[178.23870849609375, 123.7001953125, 0.199709...   
120278  [[181.7613525390625, 124.66265869140625, 0.256...   

                                                    pose1  
0                                                     NaN  
1                                                     NaN  
2       [[594.29736328125, 60.15850830078125, 0.358740...  
3       [[579.4054565429688, 62.07275390625, 0.4552341...  
4       [[565.22314453125, 57.39752197265625, 0.498457...  
...                                                   ...  
120274  [[148.7049560546875, 139.31954956054688, 0.676...  
120275  [[148.7049560546875, 139.31954956054688, 0.676...  
120276  [[148.7049560546875, 139.31954956054688, 0.676...  
120277  [[148.7049560546875, 139.31954956054688, 0.676...  
120278  [[148.7049560546875, 139.31954956054688, 0.676...  

[120279 rows x 5 columns]

In [ ]:
df["pose1"] = df["pose1"].fillna(method='bfill')
df

position    image  frame  \
0       standing        1      1   
1       standing        2      2   
2       standing        3      3   
3       standing        4      4   
4       standing        5      5   
...          ...      ...    ...   
120274      back  1506746   6746   
120275      back  1506747   6747   
120276      back  1506748   6748   
120277      back  1506749   6749   
120278      back  1506750   6750   

                                                    pose2  \
0       [[449.349365234375, 223.6246337890625, 0.99492...   
1       [[443.377197265625, 223.846435546875, 0.989061...   
2       [[787.5810546875, 270.7499694824219, 0.9706746...   
3       [[778.1063232421875, 269.86773681640625, 0.955...   
4       [[763.244384765625, 269.6915283203125, 0.95246...   
...                                                   ...   
120274  [[189.31475830078125, 149.04867553710938, 0.25...   
120275  [[178.88967895507812, 122.95089721679688, 0.26...   
120276  [[179.33627319335938, 123.41546630859375, 0.29...   
120277  [[178.23870849609375, 123.7001953125, 0.199709...   
120278  [[181.7613525390625, 124.66265869140625, 0.256...   

                                                    pose1  
0       [[594.29736328125, 60.15850830078125, 0.358740...  
1       [[594.29736328125, 60.15850830078125, 0.358740...  
2       [[594.29736328125, 60.15850830078125, 0.358740...  
3       [[579.4054565429688, 62.07275390625, 0.4552341...  
4       [[565.22314453125, 57.39752197265625, 0.498457...  
...                                                   ...  
120274  [[148.7049560546875, 139.31954956054688, 0.676...  
120275  [[148.7049560546875, 139.31954956054688, 0.676...  
120276  [[148.7049560546875, 139.31954956054688, 0.676...  
120277  [[148.7049560546875, 139.31954956054688, 0.676...  
120278  [[148.7049560546875, 139.31954956054688, 0.676...  

[120279 rows x 5 columns]

In [ ]:
df["pose2"] = df["pose2"].fillna(method='ffill')
nan_rows = df[df.isna().any(axis=1)]


In [ ]:
len(df)

120279

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Assuming we have a DataFrame `df` with pose1 and pose2 data
pose1_data = np.stack(df['pose1'].values)
pose2_data = np.stack(df['pose2'].values)

# Combine the pose data from both players into a single array
# Each sample will now have 34 keypoints (17*2)
data = np.concatenate((pose1_data, pose2_data), axis=1)

# Reshape the data to 2D
num_samples = data.shape[0]
data = data.reshape(num_samples, -1)  # the "-1" makes reshape infer the correct size for the second dimension

# Normalize features to have zero mean and unit variance
scaler = StandardScaler()
data = scaler.fit_transform(data)

# Let's assume that the labels are in `df['position']`
labels = df['position'].values

# Encode labels to integers
le = LabelEncoder()
labels = le.fit_transform(labels)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)

# Get the number of classes
num_classes = len(np.unique(labels))

# Define the model
input_shape = data.shape[1:]  # size of the 2nd dimension of data, after reshaping

model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=input_shape),
    layers.Dense(64, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss=keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))


Epoch 1/5
3007/3007 [==============================] - 17s 4ms/step - loss: 0.4798 - accuracy: 0.8399 - val_loss: 0.2017 - val_accuracy: 0.9368
Epoch 2/5
3007/3007 [==============================] - 10s 3ms/step - loss: 0.1477 - accuracy: 0.9518 - val_loss: 0.1584 - val_accuracy: 0.9466
Epoch 3/5
3007/3007 [==============================] - 11s 4ms/step - loss: 0.0974 - accuracy: 0.9678 - val_loss: 0.0995 - val_accuracy: 0.9673
Epoch 4/5
3007/3007 [==============================] - 11s 4ms/step - loss: 0.0746 - accuracy: 0.9754 - val_loss: 0.0791 - val_accuracy: 0.9729
Epoch 5/5
3007/3007 [==============================] - 11s 4ms/step - loss: 0.0627 - accuracy: 0.9796 - val_loss: 0.0794 - val_accuracy: 0.9731


In [ ]:
from joblib import dump

# Save the scaler
dump(scaler, 'scaler.joblib')

# Save the LabelEncoder
dump(le, 'label_encoder.joblib')

['label_encoder.joblib']

In [ ]:
model.save("position_classifier.h5")

In [ ]:
# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('\nTest accuracy:', test_acc)


752/752 - 1s - loss: 0.0794 - accuracy: 0.9731 - 1s/epoch - 2ms/step

Test accuracy: 0.9731460213661194


In [ ]:
# Make predictions on the test data
predictions = model.predict(X_test)

# Convert predictions from probabilities to class labels
predicted_labels = np.argmax(predictions, axis=1)

# Now you can compare predicted_labels with y_test to analyze the model's performance


752/752 [==============================] - 1s 2ms/step


In [ ]:
X_test[0]

array([-0.85774413, -1.29351174,  0.65866062, -0.8396159 , -1.28526953,
        0.66985859, -0.85376034, -1.29942498,  0.86224624, -0.87556831,
       -1.29668074, -1.80684742, -0.90982445, -1.34007778,  0.597807  ,
       -0.93546601, -1.25673278,  0.173784  , -1.00825047, -1.35265623,
        0.77681029, -0.89865516, -1.16741846,  0.82444908, -1.03163393,
       -1.22231234,  1.02771433, -0.86472881, -0.94168812,  0.80230259,
       -1.06321725, -1.16985788,  0.71680529, -1.16994635, -1.15106715,
       -0.71924648, -1.26469072, -1.16746552, -0.369683  , -1.04534688,
       -0.85030584, -0.39942563, -1.0968698 , -0.84531536,  0.45010657,
       -1.16995638, -0.97797808, -0.91013297, -1.18532234, -0.95583759,
        0.73361902, -1.35385014, -0.8359046 ,  0.07030205, -1.35215761,
       -0.81792492,  0.44376578, -1.35729496, -0.79901934,  0.33954208,
       -1.35017864, -0.86758509,  0.63860141, -1.38011242, -0.88196077,
       -1.79329074, -1.29517723, -1.03231524,  0.57364641, -1.37

In [ ]:
# Let's compare actual vs predicted for the first 10 samples
for i in range(20, 30):
    print(f"Actual: {le.inverse_transform([y_test[i]])[0]}, Predicted: {le.inverse_transform([predicted_labels[i]])[0]}")


Actual: turtle, Predicted: turtle
Actual: turtle, Predicted: turtle
Actual: half_guard, Predicted: half_guard
Actual: back, Predicted: back
Actual: back, Predicted: back
Actual: standing, Predicted: standing
Actual: standing, Predicted: standing
Actual: takedown, Predicted: takedown
Actual: turtle, Predicted: turtle
Actual: takedown, Predicted: standing


In [ ]:
model.save('/sample_data')

In [ ]:
data

array([[ 1.00883043, -1.47958659, -3.23956375, ...,  1.93930523,
         1.84034956, -0.54453379],
       [ 0.92690881, -1.46096736, -2.60146495, ...,  1.87811951,
         1.86903349,  0.47830737],
       [ 0.84889072, -1.5064418 , -2.31563155, ...,  1.79484909,
         1.87325771,  0.44451986],
       ...,
       [-1.48565617, -0.71191898, -0.5508683 , ..., -1.30175461,
        -1.04414982, -1.97100157],
       [-1.46765006, -0.72727066, -0.89899976, ..., -1.52454649,
        -1.07863491, -2.09950968],
       [-1.44241069, -0.70961317, -1.14135812, ..., -1.23247942,
        -1.02769666, -2.1467242 ]])

In [ ]:
pose1_data

array([[[5.94297363e+02, 6.01585083e+01, 3.58740747e-01],
        [5.76469116e+02, 4.05621948e+01, 3.15121174e-01],
        [6.07318970e+02, 5.12919922e+01, 3.82933736e-01],
        ...,
        [5.84850952e+02, 4.35815369e+02, 8.60237420e-01],
        [4.99936279e+02, 6.09384094e+02, 8.29350829e-01],
        [5.22938599e+02, 5.22810974e+02, 6.36651158e-01]],

       [[5.79405457e+02, 6.20727539e+01, 4.55234140e-01],
        [5.72580750e+02, 4.97641296e+01, 3.84257764e-01],
        [6.06023987e+02, 5.82978516e+01, 3.89750510e-01],
        ...,
        [5.85568909e+02, 4.50042603e+02, 8.94262552e-01],
        [4.90440613e+02, 6.06752563e+02, 7.94921458e-01],
        [5.25087830e+02, 5.58015381e+02, 7.21611261e-01]],

       [[5.65223145e+02, 5.73975220e+01, 4.98457909e-01],
        [5.60387817e+02, 4.22384338e+01, 4.08371300e-01],
        [5.87298218e+02, 5.00549316e+01, 4.62593138e-01],
        ...,
        [5.81099487e+02, 4.50414368e+02, 8.87512267e-01],
        [4.75486938e+02, 6.10